version: '3'
services:
  potential_metrics:
    build:
      context: ../
      dockerfile: ./Docker/Dockerfile.Potential_metrics
    ports:
      - 0.0.0.0:8081:8888
    volumes:
      - ${fit_files_src}:${fit_files_dest}
    command:
      jupyter lab --NotebookApp.password='' --NotebookApp.token='' .