version: '3'
services:
  app:
    build:
      context: ../
      dockerfile: ./Docker/Dockerfile
    ports:
      - 0.0.0.0:8081:8888
    volumes:
      - ${fit_files_src}:${fit_files_dest}
    command:
      jupyter lab --NotebookApp.password='' --NotebookApp.token='' .